version: '2'
services:
    gidilibrary-app:
        image: gidilibrary
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gidilibrary-postgresql:5432/gidiLibrary
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://gidilibrary-elasticsearch:9200
        ports:
            - 8080:8080
    gidilibrary-postgresql:
        extends:
            file: postgresql.yml
            service: gidilibrary-postgresql
    gidilibrary-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gidilibrary-elasticsearch
